input { 
  kafka {
    codec => "json"
    bootstrap_servers => "kafka:29092"
    topics => ["mern_template-api_logger"]
    client_id => "mern_template-api_producer"
    group_id => "logstash"
  } 
}

filter {
  mutate {
    remove_field => ["@version", "@timestamp", "event"]
  }  
}

output {
  elasticsearch { hosts => ["http://elasticsearch:9200"]  index => "index-mern_template_api"}
  stdout {}
}